security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_manager_provider:
            entity:
                class: App\Entity\Gestionnaires
                property: email 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_manager_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
                default_target_path: app_admin_stats
            logout:
                path: app_logout
                target: app_login

    access_control:
       
        - { path: ^/admin, roles: ROLE_GESTIONNAIRE }
