# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

admin_produit_index:
    path: /admin/produits
    controller: App\Controller\Admin\ProduitController::index

admin_burger_new:
    path: /admin/produits/nouveau-burger
    controller: App\Controller\Admin\ProduitController::newBurger

admin_menu_new:
    path: /admin/produits/nouveau-menu
    controller: App\Controller\Admin\ProduitController::newMenu

admin_burger_edit:
    path: /admin/produits/modifier-burger/{id}
    controller: App\Controller\Admin\ProduitController::editBurger

admin_menu_edit:
    path: /admin/produits/modifier-menu/{id}
    controller: App\Controller\Admin\ProduitController::editMenu

admin_complement_edit:
    path: /admin/produits/modifier-complement/{id}
    controller: App\Controller\Admin\ProduitController::editComplement

# --- ARCHIVAGE ---
admin_produit_archive:
    path: /admin/produits/archive/{type}/{id}
    controller: App\Controller\Admin\ProduitController::archive

# --- ROUTES POUR LES ZONES ---

app_zones_index:
    path: /admin/zones/
    controller: App\Controller\Admin\ZonesController::index
    methods: [GET]

app_zones_new:
    path: /admin/zones/new
    controller: App\Controller\Admin\ZonesController::new
    methods: [GET, POST]

app_zones_edit:
    path: /admin/zones/{id}/edit
    controller: App\Controller\Admin\ZonesController::edit
    methods: [GET, POST]

app_zones_delete:
    path: /admin/zones/{id}
    controller: App\Controller\Admin\ZonesController::delete
    methods: [POST]

# --- ROUTES POUR LES COMMANDES ---

app_admin_commandes_index:
    path: /admin/commandes
    controller: App\Controller\Admin\CommandeGestionController::index
    methods: [GET]

app_admin_commandes_change_status:
    path: /admin/commandes/{id}/status/{newStatus}
    controller: App\Controller\Admin\CommandeGestionController::changeStatus
    methods: [GET]

app_admin_commandes_assign:
    path: /admin/commandes/assign-livreur
    controller: App\Controller\Admin\CommandeGestionController::assignLivreur
    methods: [POST]

# --- ROUTES POUR LES STATS ---
app_admin_stats:
    path: /admin/stats
    controller: App\Controller\Admin\StatsController::index