# config/services.yaml

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Chargement automatique de toutes les classes dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Note bien : Cette ligne commence TOUT AU DEBUT de la marge (4 espaces ou alignée sur App\:)
    App\Controller\ZonesController:
        tags: ['controller.service_arguments']